//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "(" Type() ")" UnaryExpression()
 *       | "(" Type() ")" UnaryExpressionNotPlusMinus()
 * </PRE>
 */
public class CastExpression implements Node {
   public NodeChoice f0;

   public CastExpression(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

