//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "{"
 * f1 -> ( ClassBodyDeclaration() )*
 * f2 -> "}"
 * </PRE>
 */
public class ClassBody implements Node {
   public NodeToken f0;
   public NodeListOptional f1;
   public NodeToken f2;

   public ClassBody(NodeToken n0, NodeListOptional n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public ClassBody(NodeListOptional n0) {
      f0 = new NodeToken("{");
      f1 = n0;
      f2 = new NodeToken("}");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

