//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ";"
 * </PRE>
 */
public class EmptyStatement implements Node {
   public NodeToken f0;

   public EmptyStatement(NodeToken n0) {
      f0 = n0;
   }

   public EmptyStatement() {
      f0 = new NodeToken(";");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

