//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> InstanceOfExpression()
 * f1 -> ( ( "==" | "!=" ) InstanceOfExpression() )*
 * </PRE>
 */
public class EqualityExpression implements Node {
   public InstanceOfExpression f0;
   public NodeListOptional f1;

   public EqualityExpression(InstanceOfExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

