//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> AndExpression()
 * f1 -> ( "^" AndExpression() )*
 * </PRE>
 */
public class ExclusiveOrExpression implements Node {
   public AndExpression f0;
   public NodeListOptional f1;

   public ExclusiveOrExpression(AndExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

