//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ConditionalExpression()
 * f1 -> [ AssignmentOperator() Expression() ]
 * </PRE>
 */
public class Expression implements Node {
   public ConditionalExpression f0;
   public NodeOptional f1;

   public Expression(ConditionalExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

