//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "("
 * f1 -> [ FormalParameter() ( "," FormalParameter() )* ]
 * f2 -> ")"
 * </PRE>
 */
public class FormalParameters implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeToken f2;

   public FormalParameters(NodeToken n0, NodeOptional n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FormalParameters(NodeOptional n0) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = new NodeToken(")");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

