//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> StatementExpressionList()
 * </PRE>
 */
public class ForUpdate implements Node {
   public StatementExpressionList f0;

   public ForUpdate(StatementExpressionList n0) {
      f0 = n0;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

