//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> [ "static" ]
 * f1 -> Block()
 * </PRE>
 */
public class Initializer implements Node {
   public NodeOptional f0;
   public Block f1;

   public Initializer(NodeOptional n0, Block n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

