//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> RelationalExpression()
 * f1 -> [ "instanceof" Type() ]
 * </PRE>
 */
public class InstanceOfExpression implements Node {
   public RelationalExpression f0;
   public NodeOptional f1;

   public InstanceOfExpression(RelationalExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

