//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ( "abstract" | "public" )*
 * f1 -> UnmodifiedInterfaceDeclaration()
 * </PRE>
 */
public class InterfaceDeclaration implements Node {
   public NodeListOptional f0;
   public UnmodifiedInterfaceDeclaration f1;

   public InterfaceDeclaration(NodeListOptional n0, UnmodifiedInterfaceDeclaration n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

