//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> [ "final" ]
 * f1 -> Type()
 * f2 -> VariableDeclarator()
 * f3 -> ( "," VariableDeclarator() )*
 * </PRE>
 */
public class LocalVariableDeclaration implements Node {
   public NodeOptional f0;
   public Type f1;
   public VariableDeclarator f2;
   public NodeListOptional f3;

   public LocalVariableDeclaration(NodeOptional n0, Type n1, VariableDeclarator n2, NodeListOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

