//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ( "public" | "protected" | "private" | "static" | "abstract" | "final" | "native" | "synchronized" )*
 * f1 -> ResultType()
 * f2 -> &lt;IDENTIFIER&gt;
 * f3 -> "("
 * </PRE>
 */
public class MethodDeclarationLookahead implements Node {
   public NodeListOptional f0;
   public ResultType f1;
   public NodeToken f2;
   public NodeToken f3;

   public MethodDeclarationLookahead(NodeListOptional n0, ResultType n1, NodeToken n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public MethodDeclarationLookahead(NodeListOptional n0, ResultType n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = new NodeToken("(");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

