//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ( "public" | "protected" | "private" | "static" | "abstract" | "final" | "native" | "synchronized" )*
 * f1 -> ResultType()
 * f2 -> MethodDeclarator()
 * f3 -> [ "throws" NameList() ]
 * f4 -> ( Block() | ";" )
 * </PRE>
 */
public class MethodDeclaration implements Node {
   public NodeListOptional f0;
   public ResultType f1;
   public MethodDeclarator f2;
   public NodeOptional f3;
   public NodeChoice f4;

   public MethodDeclaration(NodeListOptional n0, ResultType n1, MethodDeclarator n2, NodeOptional n3, NodeChoice n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

