//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> UnaryExpression()
 * f1 -> ( ( "*" | "/" | "%" ) UnaryExpression() )*
 * </PRE>
 */
public class MultiplicativeExpression implements Node {
   public UnaryExpression f0;
   public NodeListOptional f1;

   public MultiplicativeExpression(UnaryExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

