//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> Name()
 * f1 -> ( "," Name() )*
 * </PRE>
 */
public class NameList implements Node {
   public Name f0;
   public NodeListOptional f1;

   public NameList(Name n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

