//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(jde.parser.visitor.Visitor v);

}

