//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
   public NodeChoice(Node node) {
      this(node, -1);
   }

   public NodeChoice(Node node, int whichChoice) {
      choice = node;
      which = whichChoice;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      choice.accept(v);
   }

   public Node choice;
   public int which;
}

