//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "null"
 * </PRE>
 */
public class NullLiteral implements Node {
   public NodeToken f0;

   public NullLiteral(NodeToken n0) {
      f0 = n0;
   }

   public NullLiteral() {
      f0 = new NodeToken("null");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

