//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "package"
 * f1 -> Name()
 * f2 -> ";"
 * </PRE>
 */
public class PackageDeclaration implements Node {
   public NodeToken f0;
   public Name f1;
   public NodeToken f2;

   public PackageDeclaration(NodeToken n0, Name n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public PackageDeclaration(Name n0) {
      f0 = new NodeToken("package");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

