//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "++"
 * f1 -> PrimaryExpression()
 * </PRE>
 */
public class PreIncrementExpression implements Node {
   public NodeToken f0;
   public PrimaryExpression f1;

   public PreIncrementExpression(NodeToken n0, PrimaryExpression n1) {
      f0 = n0;
      f1 = n1;
   }

   public PreIncrementExpression(PrimaryExpression n0) {
      f0 = new NodeToken("++");
      f1 = n0;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

