//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "boolean"
 *       | "char"
 *       | "byte"
 *       | "short"
 *       | "int"
 *       | "long"
 *       | "float"
 *       | "double"
 * </PRE>
 */
public class PrimitiveType implements Node {
   public NodeChoice f0;

   public PrimitiveType(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

