//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "." "this"
 *       | "." AllocationExpression()
 *       | "[" Expression() "]"
 *       | "." &lt;IDENTIFIER&gt;
 *       | Arguments()
 * </PRE>
 */
public class PrimarySuffix implements Node {
   public NodeChoice f0;

   public PrimarySuffix(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

