//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> PrimaryPrefix()
 * f1 -> ( PrimarySuffix() )*
 * </PRE>
 */
public class PrimaryExpression implements Node {
   public PrimaryPrefix f0;
   public NodeListOptional f1;

   public PrimaryExpression(PrimaryPrefix n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

