//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> StatementExpression()
 * f1 -> ( "," StatementExpression() )*
 * </PRE>
 */
public class StatementExpressionList implements Node {
   public StatementExpression f0;
   public NodeListOptional f1;

   public StatementExpressionList(StatementExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

