//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "throw"
 * f1 -> Expression()
 * f2 -> ";"
 * </PRE>
 */
public class ThrowStatement implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeToken f2;

   public ThrowStatement(NodeToken n0, Expression n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public ThrowStatement(Expression n0) {
      f0 = new NodeToken("throw");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

