//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "try"
 * f1 -> Block()
 * f2 -> ( "catch" "(" FormalParameter() ")" Block() )*
 * f3 -> [ "finally" Block() ]
 * </PRE>
 */
public class TryStatement implements Node {
   public NodeToken f0;
   public Block f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public TryStatement(NodeToken n0, Block n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public TryStatement(Block n0, NodeListOptional n1, NodeOptional n2) {
      f0 = new NodeToken("try");
      f1 = n0;
      f2 = n1;
      f3 = n2;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

