//
// Generated by JTB 1.1.2
//

package jde.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;IDENTIFIER&gt;
 * f1 -> ( "[" "]" )*
 * </PRE>
 */
public class VariableDeclaratorId implements Node {
   public NodeToken f0;
   public NodeListOptional f1;

   public VariableDeclaratorId(NodeToken n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jde.parser.visitor.Visitor v) {
      v.visit(this);
   }
}

